// <auto-generated />
namespace NL4_Vanderperre_Lucas_Laureyns_Piet_WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Notificaties1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notificaties1));
        
        string IMigrationMetadata.Id
        {
            get { return "201812151638281_Notificaties1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
